// Generated by CoffeeScript 1.10.0
(function() {
  var Config, fs;

  fs = require('fs');

  Config = (function() {
    var _config;

    function Config() {}

    _config = void 0;

    Config.get = function() {
      return _config != null ? _config : _config = JSON.parse(fs.readFileSync(__dirname + '/../config/fnfc.json'));
    };

    return Config;

  })();

  module.exports = {
    Config: Config
  };

}).call(this);
