// Generated by CoffeeScript 1.10.0
(function() {
  var Config, DbClient, MongoClient;

  MongoClient = require('mongodb').MongoClient;

  Config = require('./config').Config;

  DbClient = (function() {
    function DbClient(callback) {
      this.config = Config.get();
      MongoClient.connect("mongodb://" + this.config.mongodb.ip + ":" + this.config.mongodb.port + "/" + this.config.mongodb.db, (function(_this) {
        return function(err, db) {
          if (err) {
            return callback(err);
          } else {
            return callback(null, db);
          }
        };
      })(this));
    }

    return DbClient;

  })();

  module.exports = {
    DbClient: DbClient
  };

}).call(this);
