// Generated by CoffeeScript 1.8.0
(function() {
  var Config, ElasticSearch, ElasticsearchDao;

  ElasticSearch = require('elasticsearch');

  Config = require('./config').Config;

  ElasticsearchDao = (function() {
    function ElasticsearchDao(db) {
      this.client = new ElasticSearch.Client({
        host: 'localhost:9200',
        log: 'trace'
      });
    }

    ElasticsearchDao.prototype.insert = function(records) {
      var body, record, _i, _len;
      body = [];
      for (_i = 0, _len = records.length; _i < _len; _i++) {
        record = records[_i];
        body.push({
          index: {
            _index: 'netflow',
            _type: 'records'
          }
        });
        body.push(record);
      }
      console.log(body);
      return this.client.bulk({
        body: body
      }, function(err, result) {
        if (err) {
          throw err;
        }
      });
    };

    return ElasticsearchDao;

  })();

  module.exports = {
    ElasticsearchDao: ElasticsearchDao
  };

}).call(this);
