// Generated by CoffeeScript 1.10.0
(function() {
  var Logger, winston;

  winston = require('winston');

  Logger = (function() {
    var _instance;

    function Logger() {}

    _instance = void 0;

    Logger.get = function(level) {
      return _instance != null ? _instance : _instance = new winston.Logger({
        transports: [
          new winston.transports.Console({
            timestamp: true,
            colorize: true,
            level: level
          })
        ]
      });
    };

    return Logger;

  })();

  module.exports = {
    Logger: Logger
  };

}).call(this);
