// Generated by CoffeeScript 1.10.0
(function() {
  var Config, RecordDao;

  Config = require('./config').Config;

  RecordDao = (function() {
    function RecordDao(db) {
      this.config = Config.get();
      this.collection = db.collection(this.config.mongodb.collection.records);
    }

    RecordDao.prototype.insert = function(records) {
      return this.collection.insert(records, function(err, result) {
        if (err) {
          throw err;
        }
      });
    };

    return RecordDao;

  })();

  module.exports = {
    RecordDao: RecordDao
  };

}).call(this);
