// Generated by CoffeeScript 1.10.0
(function() {
  var Record;

  Record = (function() {
    function Record() {
      this.template_id = null;
      this.exporter = null;
      this.record = {};
    }

    return Record;

  })();

  module.exports = {
    Record: Record
  };

}).call(this);
