// Generated by CoffeeScript 1.10.0
(function() {
  var Config, TemplateDao;

  Config = require('./config').Config;

  TemplateDao = (function() {
    var _cache;

    _cache = {};

    function TemplateDao(db) {
      this.config = Config.get();
      this.collection = db.collection(this.config.mongodb.collection.template);
    }

    TemplateDao.prototype.put = function(template) {
      return this.collection.save(template, function(err, result) {
        if (err) {
          throw err;
        }
        return _cache[template._id] = template;
      });
    };

    TemplateDao.prototype.get = function(id, callback) {
      var template;
      template = _cache[id];
      if (typeof template === "undefined") {
        return this.collection.findOne({
          _id: id
        }, function(err, result) {
          if (err) {
            return callback(err);
          } else {
            if (result) {
              _cache[id] = result;
              return callback(null, result);
            } else {

            }
          }
        });
      } else {
        return callback(null, template);
      }
    };

    return TemplateDao;

  })();

  module.exports = {
    TemplateDao: TemplateDao
  };

}).call(this);
